return {
  'jakewvincent/mkdnflow.nvim',
  ft = { 'markdown' },
  opts = {
    mappings = {
      MkdnEnter = false, -- MkdnEnter = { { 'n', 'v' }, '<CR>' },
      MkdnTab = false,
      MkdnSTab = false,
      MkdnNextLink = { 'n', '<Tab>' },
      MkdnPrevLink = { 'n', '<S-Tab>' },
      MkdnNextHeading = { 'n', ']]' },
      MkdnPrevHeading = { 'n', '[[' },
      MkdnGoBack = { 'n', '<BS>' },
      MkdnGoForward = { 'n', '<Del>' },
      MkdnCreateLink = { 'n', '<leader>mc' },
      MkdnCreateLinkFromClipboard = { { 'n', 'v' }, '<leader>mp' },
      MkdnFollowLink = { 'n', '<leader>m<CR>' }, -- see MkdnEnter
      MkdnDestroyLink = { 'n', '<leader>md' },
      MkdnTagSpan = { 'v', '<M-CR>' },
      MkdnMoveSource = { 'n', '<F2>' },
      MkdnYankAnchorLink = { 'n', '<leader>mya' },
      MkdnYankFileAnchorLink = { 'n', '<leader>myf' },
      MkdnIncreaseHeading = { 'n', '<<' }, -- = { 'n', '+' },
      MkdnDecreaseHeading = { 'n', '>>' }, -- = { 'n', '-' },
      MkdnToggleToDo = { { 'n', 'v' }, '<C-Space>' },
      MkdnNewListItem = false,
      MkdnNewListItemBelowInsert = { { 'n', 'i' }, '<M-CR>' },
      MkdnNewListItemAboveInsert = { { 'n', 'i' }, '<S-M-CR>' },
      MkdnExtendList = false,
      MkdnUpdateNumbering = { 'n', '<leader>mn' },
      MkdnTableNextCell = { 'i', '<Tab>' },
      MkdnTablePrevCell = { 'i', '<S-Tab>' },
      MkdnTableNextRow = false,
      MkdnTablePrevRow = { 'i', '<M-CR>' },
      MkdnTableNewRowBelow = { 'n', '<leader>ir' },
      MkdnTableNewRowAbove = { 'n', '<leader>iR' },
      MkdnTableNewColAfter = { 'n', '<leader>ic' },
      MkdnTableNewColBefore = { 'n', '<leader>iC' },
      MkdnFoldSection = { 'n', '<leader>mf' },
      MkdnUnfoldSection = { 'n', '<leader>mF' },
    },
  },
}
